
  const destinos = [
    {
        titulo: 'Viagem Gastronômica',
        destinos: 'Bento Gonçalves / Carlos Barbosa / Garibaldi',
        descricao: '',
        dataInicio: '08/11/2024',
        dataRetorno: '08/11/2024',
        lugaresDisponiveis: '',
        valor: '',
        imagens: [jp.png,many.jpg],
      },{
        titulo: '',
        destinos: 'Buenos Aires / Betel / Tigre / Campanópolis ',
        descricao: '',
        dataInicio: 'NaN/NaN/NaN',
        dataRetorno: 'NaN/NaN/NaN',
        lugaresDisponiveis: '',
        valor: '',
        imagens: [],
      },{
        titulo: '',
        destinos: '',
        descricao: '',
        dataInicio: 'NaN/NaN/NaN',
        dataRetorno: 'NaN/NaN/NaN',
        lugaresDisponiveis: '',
        valor: '',
        imagens: [],
      },{
        titulo: '',
        destinos: 'Maria Fumaça / Epopeia Italiana ',
        descricao: '',
        dataInicio: '09/01/2024',
        dataRetorno: '09/01/2024',
        lugaresDisponiveis: '',
        valor: '',
        imagens: [],
      },{
        titulo: '',
        destinos: 'Termas Marcelino Ramos ',
        descricao: '',
        dataInicio: '09/06/2024',
        dataRetorno: '09/08/2024',
        lugaresDisponiveis: '',
        valor: '',
        imagens: [],
      },{
        titulo: '',
        destinos: '',
        descricao: '',
        dataInicio: 'NaN/NaN/NaN',
        dataRetorno: 'NaN/NaN/NaN',
        lugaresDisponiveis: '',
        valor: '',
        imagens: [],
      },{
        titulo: '',
        destinos: '',
        descricao: '',
        dataInicio: 'NaN/NaN/NaN',
        dataRetorno: 'NaN/NaN/NaN',
        lugaresDisponiveis: '',
        valor: '',
        imagens: [],
      },{
        titulo: '',
        destinos: '',
        descricao: '',
        dataInicio: 'NaN/NaN/NaN',
        dataRetorno: 'NaN/NaN/NaN',
        lugaresDisponiveis: '',
        valor: '',
        imagens: [],
      },{
        titulo: '',
        destinos: '',
        descricao: '',
        dataInicio: 'NaN/NaN/NaN',
        dataRetorno: 'NaN/NaN/NaN',
        lugaresDisponiveis: '',
        valor: '',
<<<<<<< Updated upstream
        imagens: [],
      },{
        titulo: '',
        destinos: '',
        descricao: '',
        dataInicio: 'NaN/NaN/NaN',
        dataRetorno: 'NaN/NaN/NaN',
        lugaresDisponiveis: '',
        valor: '',
        imagens: [],
      },
  ]
=======
        imagens: []
    },
];

>>>>>>> Stashed changes
